<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'name'             => 'Faris Fudhali',
                'email'            => 'faris@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '081234567890',
                'lokasi'           => 'Banda Aceh',
                'gol_darah'        => 'A',
                'rhesus'           => '+',
                'berat_badan'      => 68,
                'usia'             => 22,
                'catatan_kesehatan'=> 'Tidak ada penyakit kronis',
                'is_donor'         => true,
                'status_donor'     => 'Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Rina Marlina',
                'email'            => 'rina@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '082345678901',
                'lokasi'           => 'Banda Aceh',
                'gol_darah'        => 'B',
                'rhesus'           => '+',
                'berat_badan'      => 55,
                'usia'             => 25,
                'catatan_kesehatan'=> 'Sehat',
                'is_donor'         => true,
                'status_donor'     => 'Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Budi Santoso',
                'email'            => 'budi@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '083456789012',
                'lokasi'           => 'Aceh Besar',
                'gol_darah'        => 'O',
                'rhesus'           => '+',
                'berat_badan'      => 72,
                'usia'             => 30,
                'catatan_kesehatan'=> 'Tidak ada riwayat penyakit',
                'is_donor'         => true,
                'status_donor'     => 'Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Siti Aminah',
                'email'            => 'siti@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '084567890123',
                'lokasi'           => 'Lhokseumawe',
                'gol_darah'        => 'AB',
                'rhesus'           => '+',
                'berat_badan'      => 50,
                'usia'             => 28,
                'catatan_kesehatan'=> 'Sehat, rutin olahraga',
                'is_donor'         => true,
                'status_donor'     => 'Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Rizal Fahmi',
                'email'            => 'rizal@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '085678901234',
                'lokasi'           => 'Sabang',
                'gol_darah'        => 'A',
                'rhesus'           => '-',
                'berat_badan'      => 65,
                'usia'             => 27,
                'catatan_kesehatan'=> 'Tidak ada kontraindikasi',
                'is_donor'         => true,
                'status_donor'     => 'Tidak Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Dewi Rahayu',
                'email'            => 'dewi@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '086789012345',
                'lokasi'           => 'Banda Aceh',
                'gol_darah'        => 'O',
                'rhesus'           => '-',
                'berat_badan'      => 52,
                'usia'             => 23,
                'catatan_kesehatan'=> 'Sehat',
                'is_donor'         => true,
                'status_donor'     => 'Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Ahmad Zaki',
                'email'            => 'zaki@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '087890123456',
                'lokasi'           => 'Aceh Utara',
                'gol_darah'        => 'B',
                'rhesus'           => '-',
                'berat_badan'      => 70,
                'usia'             => 35,
                'catatan_kesehatan'=> 'Tekanan darah normal',
                'is_donor'         => false,
                'status_donor'     => 'Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Nurul Huda',
                'email'            => 'nurul@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '088901234567',
                'lokasi'           => 'Pidie',
                'gol_darah'        => 'A',
                'rhesus'           => '+',
                'berat_badan'      => 58,
                'usia'             => 21,
                'catatan_kesehatan'=> 'Tidak ada penyakit bawaan',
                'is_donor'         => true,
                'status_donor'     => 'Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Hafiz Maulana',
                'email'            => 'hafiz@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '089012345678',
                'lokasi'           => 'Banda Aceh',
                'gol_darah'        => 'AB',
                'rhesus'           => '-',
                'berat_badan'      => 75,
                'usia'             => 32,
                'catatan_kesehatan'=> 'Sehat jasmani dan rohani',
                'is_donor'         => true,
                'status_donor'     => 'Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Mira Susanti',
                'email'            => 'mira@example.com',
                'password'         => Hash::make('password123'),
                'no_telepon'       => '081298765432',
                'lokasi'           => 'Aceh Tengah',
                'gol_darah'        => 'O',
                'rhesus'           => '+',
                'berat_badan'      => 54,
                'usia'             => 26,
                'catatan_kesehatan'=> 'Tidak ada kontraindikasi',
                'is_donor'         => true,
                'status_donor'     => 'Tersedia',
                'role'             => 'user',
            ],
            [
                'name'             => 'Admin BloodConnect',
                'email'            => 'admin@bloodconnect.id',
                'password'         => Hash::make('admin123'),
                'no_telepon'       => '081100000000',
                'lokasi'           => 'Banda Aceh',
                'gol_darah'        => null,
                'rhesus'           => null,
                'berat_badan'      => null,
                'usia'             => null,
                'catatan_kesehatan'=> null,
                'is_donor'         => false,
                'status_donor'     => null,
                'role'             => 'admin',
            ],
        ];

        foreach ($users as $data) {
            // Pakai firstOrCreate agar tidak duplikat jika seeder dijalankan ulang
            User::firstOrCreate(['email' => $data['email']], $data);
        }
    }
}
